AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
# lembrar de mudar o nome das buckets para a que cada um usa!!!

Resources:
  # API Gateway para Upload de Notas Fiscais
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowOrigin: "'http://127.0.0.1:5500'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowMethods: "'OPTIONS,GET,POST,PUT,DELETE'"
        AllowCredentials: true
      BinaryMediaTypes:
        - "multipart/form-data"
  NLTKLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: NLTKLayer
      Description: Layer contendo a biblioteca NLTK
      ContentUri: layer/NLTK_layer.zip
      CompatibleRuntimes:
        - python3.12
      RetentionPolicy: Delete

  # Lambda para Upload de Notas Fiscais
  InvoiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.12
      CodeUri: lambda_api_gateway
      MemorySize: 256
      Timeout: 30
      Policies:
        - S3CrudPolicy:
            BucketName: minhas-notas-fiscaiss
        - Statement:
            Effect: Allow
            Action: 
              - states:StartExecution
              - states:ListExecutions
              - states:DescribeExecution
              - states:GetExecutionHistory
            Resource: !Ref InvoiceProcessorStateMachine
      Environment:
        Variables:
          BUCKET_NAME: minhas-notas-fiscaiss
          STEP_FUNCTION_ARN: !Ref InvoiceProcessorStateMachine  
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/v1/invoice
            Method: POST
            RestApiId: !Ref Api

  # 📌 Bucket para armazenar as notas fiscais
  MinhasNotasFiscaisBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: minhas-notas-fiscaiss

  # 📌 Step Function para processar notas fiscais
  InvoiceProcessorStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      RoleArn: !GetAtt StepFunctionRole.Arn
      DefinitionString: !Sub |
        {
          "Comment": "Processa as notas fiscais após o upload",
          "StartAt": "ExtrairDadosTextract",
          "States": {
            "ExtrairDadosTextract": {
              "Type": "Task",
              "Resource": "${LambdaTextract.Arn}",
              "Next": "AnalisarDadosNLTK"
            },
            "AnalisarDadosNLTK": {
              "Type": "Task",
              "Resource": "${LambdaNLTK.Arn}",
              "Next": "ProcessarComLLM"
            },
            "ProcessarComLLM": {
              "Type": "Task",
              "Resource": "${LambdaLLM.Arn}",
              "End": true
            }
          }
        }

  # 📌 IAM Role para Step Functions
  StepFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - "states.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: StepFunctionLambdaInvokePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 
                  - "lambda:InvokeFunction"
                Resource: 
                  - !GetAtt LambdaTextract.Arn
                  - !GetAtt LambdaNLTK.Arn
                  - !GetAtt LambdaLLM.Arn

  # 📌 Lambda Textract - Processa OCR e chama a Lambda NLTK
  LambdaTextract:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.12
      CodeUri: lambda_textract
      MemorySize: 512
      Timeout: 60
      Role: !GetAtt LambdaTextractRole.Arn
      Environment:
        Variables:
          NEXT_LAMBDA_NLTK: !Ref LambdaNLTK
          BUCKET_NAME: minhas-notas-fiscaiss
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref MinhasNotasFiscaisBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: NFs/

  # 📌 IAM Role para a Lambda Textract
  LambdaTextractRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: TextractS3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: !Sub "arn:aws:s3:::minhas-notas-fiscaiss/*"
              - Effect: Allow
                Action:
                  - textract:AnalyzeDocument
                Resource: "*"
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: !GetAtt LambdaNLTK.Arn
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  # 📌 Lambda NLTK - Estrutura os dados extraídos do Textract
  LambdaNLTK:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: LambdaNLTK
      Handler: app.lambda_handler
      Runtime: python3.12
      CodeUri: lambda_nltk
      Layers:
        - !Ref NLTKLayer
      MemorySize: 512
      Timeout: 60
      Role: !GetAtt LambdaNLTKRole.Arn

  # 📌 IAM Role para a Lambda NLTK
  LambdaNLTKRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LogPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: !Sub "arn:aws:s3:::minhas-notas-fiscaiss/*"

  LambdaLLMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LogPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: !Sub "arn:aws:s3:::minhas-notas-fiscaiss/*"

# 🖥 Lambda LLM - Envia os dados para a API de uma LLM e armazena o resultado
  LambdaLLM:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: LambdaLLM
      Handler: app.lambda_handler
      Runtime: python3.12
      CodeUri: lambda_llm
      MemorySize: 512
      Timeout: 60
      Role: !GetAtt LambdaLLMRole.Arn


Outputs:
  # 📌 URL para chamar a API Gateway
  ApiGatewayInvokeURL:
    Description: "URL para chamar a API Gateway"
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com/Prod/api/v1/invoice"
